(define (domain Jenga)
(:requirements :strips :typing :equality :conditional-effects :existential-preconditions :universal-preconditions)
(:types 
	goalLoc
	jenga
	tabletop
	gripper
	pickupstation
)

(:constants 
	goalLoc_Const - goalLoc
 )

(:predicates 
	(goalLoc_jenga_0 ?x - goalLoc ?y - jenga)
	(goalLoc_jenga_1 ?x - goalLoc ?y - jenga)
	(goalLoc_jenga_2 ?x - goalLoc ?y - jenga)
	(jenga_jenga_0 ?x - jenga ?y - jenga)
	(jenga_jenga_1 ?x - jenga ?y - jenga)
	(jenga_jenga_2 ?x - jenga ?y - jenga)
	(jenga_jenga_3 ?x - jenga ?y - jenga)
	(jenga_jenga_4 ?x - jenga ?y - jenga)
	(jenga_jenga_5 ?x - jenga ?y - jenga)
	(jenga_jenga_6 ?x - jenga ?y - jenga)
	(jenga_jenga_7 ?x - jenga ?y - jenga)
	(jenga_jenga_8 ?x - jenga ?y - jenga)
	(gripper_jenga_0 ?x - gripper ?y - jenga)
	(gripper_jenga_1 ?x - gripper ?y - jenga)
	(gripper_jenga_2 ?x - gripper ?y - jenga)
	(clear3_gripper_jenga_1 ?x - gripper)
	(clear3_jenga_jenga_6 ?x - jenga)
	(clear3_jenga_jenga_2 ?x - jenga)
	(clear3_jenga_jenga_3 ?x - jenga)
	(clear3_jenga_jenga_1 ?x - jenga)
	(clear3_jenga_jenga_8 ?x - jenga)
	(clear3_gripper_jenga_2 ?x - gripper)
	(clear3_jenga_jenga_4 ?x - jenga)
	(clear3_jenga_jenga_7 ?x - jenga)
	(clear3_jenga_jenga_5 ?x - jenga)
)

(:action a1 
:parameters ( ?jenga_p1 - jenga  ?gripper_extra_p1 - gripper )
:precondition (and 
	(goalLoc_jenga_0 goalLoc_Const ?jenga_p1)
	(gripper_jenga_1 ?gripper_extra_p1 ?jenga_p1)
) 
:effect (and 
 	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1) 
	(not (goalLoc_jenga_0 goalLoc_Const ?jenga_p1))
	(not (goalLoc_jenga_2 goalLoc_Const ?jenga_p1))
 ) 
)

(:action a2 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(gripper_jenga_0 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_1 ?gripper_p1) 
	(clear3_gripper_jenga_2 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_2 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_0 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_1 ?gripper_p1 ?jenga_p1))
	(not (clear3_gripper_jenga_2 ?gripper_p1)) 
 ) 
)

(:action a3 
:parameters ( ?jenga_p2 - jenga  ?jenga_p3 - jenga  ?jenga_p1 - jenga  ?gripper_extra_p1 - gripper )
:precondition (and 
	(not (= ?jenga_p2 ?jenga_p3))
	(not (= ?jenga_p2 ?jenga_p1))
	(not (= ?jenga_p3 ?jenga_p1))
	(goalLoc_jenga_0 goalLoc_Const ?jenga_p2)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p3)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p1)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p3)
	(gripper_jenga_1 ?gripper_extra_p1 ?jenga_p2)
	(jenga_jenga_0 ?jenga_p1 ?jenga_p2)
	(jenga_jenga_0 ?jenga_p3 ?jenga_p2)
	(clear3_jenga_jenga_1 ?jenga_p1) 
	(clear3_jenga_jenga_1 ?jenga_p2) 
	(clear3_jenga_jenga_1 ?jenga_p3) 
	(clear3_jenga_jenga_3 ?jenga_p1) 
	(clear3_jenga_jenga_3 ?jenga_p2) 
	(clear3_jenga_jenga_3 ?jenga_p3) 
) 
:effect (and 
 	(goalLoc_jenga_1 goalLoc_Const ?jenga_p2) 
	(jenga_jenga_1 ?jenga_p1 ?jenga_p2) 
	(jenga_jenga_3 ?jenga_p3 ?jenga_p2) 
	(not (goalLoc_jenga_0 goalLoc_Const ?jenga_p2))
	(not (goalLoc_jenga_2 goalLoc_Const ?jenga_p2))
	(not (jenga_jenga_0 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_0 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_1 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_2 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_2 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_3 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_4 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_4 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_5 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_5 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_6 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_6 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_7 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_7 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_8 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_8 ?jenga_p3 ?jenga_p2))
	(not (clear3_jenga_jenga_1 ?jenga_p1)) 
	(not (clear3_jenga_jenga_3 ?jenga_p3)) 
 ) 
)

(:action a4 
:parameters ( ?jenga_p2 - jenga  ?jenga_p3 - jenga  ?jenga_p1 - jenga  ?gripper_extra_p1 - gripper )
:precondition (and 
	(not (= ?jenga_p2 ?jenga_p3))
	(not (= ?jenga_p2 ?jenga_p1))
	(not (= ?jenga_p3 ?jenga_p1))
	(goalLoc_jenga_0 goalLoc_Const ?jenga_p1)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p2)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p3)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p2)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p3)
	(gripper_jenga_1 ?gripper_extra_p1 ?jenga_p1)
	(jenga_jenga_0 ?jenga_p2 ?jenga_p1)
	(jenga_jenga_0 ?jenga_p3 ?jenga_p1)
	(clear3_jenga_jenga_2 ?jenga_p1) 
	(clear3_jenga_jenga_2 ?jenga_p2) 
	(clear3_jenga_jenga_2 ?jenga_p3) 
	(clear3_jenga_jenga_8 ?jenga_p1) 
	(clear3_jenga_jenga_8 ?jenga_p2) 
	(clear3_jenga_jenga_8 ?jenga_p3) 
) 
:effect (and 
 	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1) 
	(jenga_jenga_2 ?jenga_p2 ?jenga_p1) 
	(jenga_jenga_8 ?jenga_p3 ?jenga_p1) 
	(not (goalLoc_jenga_0 goalLoc_Const ?jenga_p1))
	(not (goalLoc_jenga_2 goalLoc_Const ?jenga_p1))
	(not (jenga_jenga_0 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_0 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_1 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_1 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_2 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_3 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_3 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_4 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_4 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_5 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_5 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_6 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_6 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_7 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_7 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_8 ?jenga_p2 ?jenga_p1))
	(not (clear3_jenga_jenga_2 ?jenga_p2)) 
	(not (clear3_jenga_jenga_8 ?jenga_p3)) 
 ) 
)

(:action a5 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1)
	(gripper_jenga_1 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_2 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_2 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_0 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_1 ?gripper_p1 ?jenga_p1))
	(clear3_gripper_jenga_1 ?gripper_p1) 
	(not (clear3_gripper_jenga_2 ?gripper_p1)) 
 ) 
)

(:action a6 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1)
	(gripper_jenga_2 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_1 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_0 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_1 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_2 ?gripper_p1 ?jenga_p1))
	(clear3_gripper_jenga_2 ?gripper_p1) 
 ) 
)

(:action a7 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(gripper_jenga_2 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_1 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_1 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_0 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_2 ?gripper_p1 ?jenga_p1))
	(clear3_gripper_jenga_2 ?gripper_p1) 
	(not (clear3_gripper_jenga_1 ?gripper_p1)) 
 ) 
)

(:action a8 
:parameters ( ?jenga_p2 - jenga  ?jenga_p3 - jenga  ?jenga_p1 - jenga  ?gripper_extra_p1 - gripper )
:precondition (and 
	(not (= ?jenga_p2 ?jenga_p3))
	(not (= ?jenga_p2 ?jenga_p1))
	(not (= ?jenga_p3 ?jenga_p1))
	(goalLoc_jenga_0 goalLoc_Const ?jenga_p2)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p3)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p1)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p3)
	(gripper_jenga_1 ?gripper_extra_p1 ?jenga_p2)
	(jenga_jenga_0 ?jenga_p1 ?jenga_p2)
	(jenga_jenga_0 ?jenga_p3 ?jenga_p2)
	(clear3_jenga_jenga_4 ?jenga_p1) 
	(clear3_jenga_jenga_4 ?jenga_p2) 
	(clear3_jenga_jenga_4 ?jenga_p3) 
	(clear3_jenga_jenga_6 ?jenga_p1) 
	(clear3_jenga_jenga_6 ?jenga_p2) 
	(clear3_jenga_jenga_6 ?jenga_p3) 
) 
:effect (and 
 	(goalLoc_jenga_1 goalLoc_Const ?jenga_p2) 
	(jenga_jenga_4 ?jenga_p1 ?jenga_p2) 
	(jenga_jenga_6 ?jenga_p3 ?jenga_p2) 
	(not (goalLoc_jenga_0 goalLoc_Const ?jenga_p2))
	(not (goalLoc_jenga_2 goalLoc_Const ?jenga_p2))
	(not (jenga_jenga_0 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_0 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_1 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_1 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_2 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_2 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_3 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_3 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_4 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_5 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_5 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_6 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_7 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_7 ?jenga_p3 ?jenga_p2))
	(not (jenga_jenga_8 ?jenga_p1 ?jenga_p2))
	(not (jenga_jenga_8 ?jenga_p3 ?jenga_p2))
	(not (clear3_jenga_jenga_4 ?jenga_p1)) 
	(not (clear3_jenga_jenga_6 ?jenga_p3)) 
 ) 
)

(:action a9 
:parameters ( ?jenga_p2 - jenga  ?jenga_p3 - jenga  ?jenga_p1 - jenga  ?gripper_extra_p1 - gripper )
:precondition (and 
	(not (= ?jenga_p2 ?jenga_p3))
	(not (= ?jenga_p2 ?jenga_p1))
	(not (= ?jenga_p3 ?jenga_p1))
	(goalLoc_jenga_0 goalLoc_Const ?jenga_p1)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p2)
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p3)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p2)
	(gripper_jenga_0 ?gripper_extra_p1 ?jenga_p3)
	(gripper_jenga_1 ?gripper_extra_p1 ?jenga_p1)
	(jenga_jenga_0 ?jenga_p2 ?jenga_p1)
	(jenga_jenga_0 ?jenga_p3 ?jenga_p1)
	(clear3_jenga_jenga_5 ?jenga_p1) 
	(clear3_jenga_jenga_5 ?jenga_p2) 
	(clear3_jenga_jenga_5 ?jenga_p3) 
	(clear3_jenga_jenga_7 ?jenga_p1) 
	(clear3_jenga_jenga_7 ?jenga_p2) 
	(clear3_jenga_jenga_7 ?jenga_p3) 
) 
:effect (and 
 	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1) 
	(jenga_jenga_5 ?jenga_p2 ?jenga_p1) 
	(jenga_jenga_7 ?jenga_p3 ?jenga_p1) 
	(not (goalLoc_jenga_0 goalLoc_Const ?jenga_p1))
	(not (goalLoc_jenga_2 goalLoc_Const ?jenga_p1))
	(not (jenga_jenga_0 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_0 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_1 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_1 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_2 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_2 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_3 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_3 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_4 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_4 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_5 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_6 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_6 ?jenga_p3 ?jenga_p1))
	(not (jenga_jenga_7 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_8 ?jenga_p2 ?jenga_p1))
	(not (jenga_jenga_8 ?jenga_p3 ?jenga_p1))
	(not (clear3_jenga_jenga_5 ?jenga_p2)) 
	(not (clear3_jenga_jenga_7 ?jenga_p3)) 
 ) 
)

(:action a10 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(gripper_jenga_2 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_1 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_1 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_0 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_2 ?gripper_p1 ?jenga_p1))
	(clear3_gripper_jenga_2 ?gripper_p1) 
	(not (clear3_gripper_jenga_1 ?gripper_p1)) 
 ) 
)

(:action a11 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(gripper_jenga_0 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_1 ?gripper_p1) 
	(clear3_gripper_jenga_2 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_2 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_0 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_1 ?gripper_p1 ?jenga_p1))
	(not (clear3_gripper_jenga_2 ?gripper_p1)) 
 ) 
)

(:action a12 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1)
	(gripper_jenga_1 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_2 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_2 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_0 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_1 ?gripper_p1 ?jenga_p1))
	(clear3_gripper_jenga_1 ?gripper_p1) 
	(not (clear3_gripper_jenga_2 ?gripper_p1)) 
 ) 
)

(:action a13 
:parameters ( ?jenga_p1 - jenga  ?gripper_extra_p1 - gripper )
:precondition (and 
	(goalLoc_jenga_0 goalLoc_Const ?jenga_p1)
	(gripper_jenga_1 ?gripper_extra_p1 ?jenga_p1)
) 
:effect (and 
 	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1) 
	(not (goalLoc_jenga_0 goalLoc_Const ?jenga_p1))
 ) 
)

(:action a14 
:parameters ( ?jenga_p1 - jenga  ?gripper_p1 - gripper )
:precondition (and 
	(goalLoc_jenga_1 goalLoc_Const ?jenga_p1)
	(gripper_jenga_2 ?gripper_p1 ?jenga_p1)
	(clear3_gripper_jenga_1 ?gripper_p1) 
) 
:effect (and 
 	(gripper_jenga_0 ?gripper_p1 ?jenga_p1) 
	(not (gripper_jenga_1 ?gripper_p1 ?jenga_p1))
	(not (gripper_jenga_2 ?gripper_p1 ?jenga_p1))
	(clear3_gripper_jenga_2 ?gripper_p1) 
 ) 
)


)